apiVersion: apps/v1
kind: Deployment
metadata:
  name: flekseenko-deploy
  labels:
    project: prod
    owner: AlekseySvidlo
spec:
  selector:
    matchLabels:
      project: prod
  template:
    metadata:
      labels:
        project: prod
    spec:
      containers:
        - name: prod-web
          image: nginx:latest
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flekseenko-deploy
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource: 
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: prod-service-web
  labels:
    env: prod 
    owner: AlekseySvidlo
spec:
  selector:
    project: prod         #Будет выбирать Поды из Deploy с таким лейбллом
  ports:
    - name: web-listener
      protocol: TCP
      port: 80    #Port on LoadBalancer
      targetPort: 80   #Port on Pod
  type: LoadBalancer
