apiVersion: apps/v1
kind: Deployment
metadata:
  name: flekseenko-deply
  labels:
    project: cia
    owner: AlekseySvidlo
spec:
  replicas: 3
  selector:
    matchLabels:
      project: cia
  template:
    metadata:
      labels:
        project: cia
    spec:
      containers:
        - name: cia-web
          image: nginx:latest
          ports:
            - containerPort: 80

        - name: not-cia-web
          image: tomcat:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: two-service-two
  labels:
    env: prod
    owner: AlekseySvidlo
spec:
  type: LoadBalancer
  selector:
    project: cia
  ports:
    - name: my-web-cia-listen
      protocol: TCP
      port: 80
      targetPort: 80

    - name: not-cia-listener
      protocol: TCP
      port: 8888
      targetPort: 8080